// FSOL Code Generator - Felix OS Language
// Walks the AST and emits x86-64 NASM assembly

use crate::parser::{
    Program, Block, FunctionBlock, Statement,
    FuncAction, InspArm, CommandMapping,
};
use std::fmt::Write;

pub struct CodeGen {
    output:  String,
    data:    String,
    bss:     String,
    label:   usize,
    fn_name: String,         // current function scope for local labels
    signals: Vec<String>,    // broadcast signals we need to allocate
}

impl CodeGen {
    pub fn new() -> Self {
        CodeGen {
            output:  String::new(),
            data:    String::new(),
            bss:     String::new(),
            label:   0,
            fn_name: String::new(),
            signals: Vec::new(),
        }
    }

    fn next_label(&mut self) -> String {
        self.label += 1;
        format!("{}.L{}", self.fn_name, self.label)
    }

    fn emit(&mut self, line: &str) {
        writeln!(self.output, "{}", line).unwrap();
    }
    fn emit_label(&mut self, name: &str) {
        writeln!(self.output, "{}:", name).unwrap();
    }
    fn emit_comment(&mut self, c: &str) {
        writeln!(self.output, "    ; {}", c).unwrap();
    }
    fn emit_instr(&mut self, i: &str) {
        writeln!(self.output, "    {}", i).unwrap();
    }
    fn data(&mut self, line: &str) {
        writeln!(self.data, "    {}", line).unwrap();
    }

    // ---- top level ----

    pub fn generate(&mut self, program: &Program) -> String {
        self.emit("; FSOL Kernel - Felix OS Language");
        self.emit("; Generated by the FSOL compiler");
        self.emit("; Assemble: nasm -f elf64 mainOS.asm -o mainOS.o");
        self.emit("; Link:     ld -T linker.ld mainOS.o -o kernel.elf");
        self.emit("");
        self.emit("[BITS 64]");
        self.emit("[DEFAULT REL]");
        self.emit("");

        // built-ins we define ourselves - never extern these
        let builtins = [
            "export", "main", "panic", "dis", "print_str",
            "strcmp", "unknown_cmd",
        ];

        if !program.imports.is_empty() {
            self.emit("; --- external modules ---");
            for imp in &program.imports {
                let lower = imp.to_lowercase();
                if !builtins.contains(&lower.as_str()) {
                    self.emit(&format!("extern fsol_{}", lower));
                }
            }
            self.emit("");
        }

        self.emit("global _start");
        self.emit("global fsol_panic");
        self.emit("global fsol_dis");
        self.emit("");
        self.emit("; --- inspect functions (external) ---");
        self.emit("extern fsol_insp_load");
        self.emit("extern fsol_insp_pci");
        self.emit("extern fsol_insp_disk");
        self.emit("extern fsol_run");
        self.emit("extern fsol_changedir");
        self.emit("");
        self.emit("section .text");
        self.emit("");

        // collect ALL functions (top-level and nested) in one flat list
        let mut all_functions: Vec<FunctionBlock> = Vec::new();
        for block in &program.blocks {
            match block {
                Block::Function(f) => Self::collect_functions(f, &mut all_functions),
            }
        }

        // emit every function as a separate flat label - no nesting
        for f in &all_functions {
            self.gen_function(f);
        }

        self.emit_runtime();

        // build final output
        let text    = self.output.clone();
        let data    = self.data.clone();
        let bss     = self.bss.clone();
        let signals = self.signals.clone();

        let mut out = text;

        if !data.is_empty() {
            writeln!(out, "\nsection .data").unwrap();
            out.push_str(&data);
        }

        writeln!(out, "\nsection .bss").unwrap();
        writeln!(out, "    ; broadcast signal flags - global so stubs can set them").unwrap();
        // declare all signals as global first
        for sig in &["os1", "main", "os", "tty"] {
            writeln!(out, "global fsol_signal_{}", sig).unwrap();
        }
        for sig in &signals {
            writeln!(out, "global fsol_signal_{}", sig).unwrap();
        }
        writeln!(out, "").unwrap();
        for sig in &signals {
            writeln!(out, "    fsol_signal_{}: resb 1", sig).unwrap();
        }
        // always include core signals
        for sig in &["os1", "main", "os", "tty"] {
            if !signals.contains(&sig.to_string()) {
                writeln!(out, "    fsol_signal_{}: resb 1", sig).unwrap();
            }
        }
        out.push_str(&bss);

        out
    }

    // ---- flatten nested function tree into a list ----

    fn collect_functions(f: &FunctionBlock, out: &mut Vec<FunctionBlock>) {
        // add this function (without its nested children in the body)
        let mut flat = f.clone();
        flat.body = f.body.iter().filter(|s| !matches!(s, Statement::NestedFunction(_))).cloned().collect();
        out.push(flat);

        // recurse into nested functions
        for stmt in &f.body {
            if let Statement::NestedFunction(child) = stmt {
                Self::collect_functions(child, out);
            }
        }
    }

    // ---- function → NASM label + body ----

    fn gen_function(&mut self, f: &FunctionBlock) {
        let label = if f.name == "main" {
            "_start".to_string()
        } else {
            format!("fsol_{}", f.name.to_lowercase())
        };

        self.fn_name = label.clone();

        self.emit_label(&label);
        self.emit_instr("push rbp");
        self.emit_instr("mov  rbp, rsp");
        self.emit("");

        // at _start, pre-set all core signals so rei checks pass
        if f.name == "main" {
            self.emit_comment("pre-set all signals so rei checks pass");
            for sig in &["main", "os", "os1", "tty"] {
                self.emit_instr(&format!("mov  byte [fsol_signal_{}], 1", sig));
            }
            self.emit("");
        }

        // set the signal for this function so rei blocks can check it
        if f.name != "main" {
            self.emit_instr(&format!(
                "mov  byte [fsol_signal_{}], 1", f.name.to_lowercase()
            ));
        }

        for stmt in &f.body {
            self.gen_statement(stmt);
        }

        if f.name == "main" {
            self.emit_comment("kernel halt loop");
            self.emit_label(&format!("{}.halt", label));
            self.emit_instr("hlt");
            self.emit_instr(&format!("jmp NEAR {}.halt", label));
        } else {
            self.emit_instr("pop  rbp");
            self.emit_instr("ret");
        }
        self.emit("");
    }

    // ---- statements ----

    fn gen_statement(&mut self, stmt: &Statement) {
        match stmt {

            Statement::Call { target, body } => {
                // skip _skip placeholders from parser
                if target == "_skip" { return; }

                self.emit_comment(&format!("call {}", target));

                for m in body {
                    if let FuncAction::Imp { from, to } = &m.action {
                        self.emit_comment(&format!("register {} into {}", from, to));
                        // store module address in a known location
                        self.emit_instr(&format!(
                            "lea  rax, [fsol_{}]", from.to_lowercase()
                        ));
                        // just call the target module init
                        self.emit_instr(&format!(
                            "call fsol_{}", to.to_lowercase()
                        ));
                    }
                }

                if target.starts_with("insp") {
                    // insp is handled as part of the Insp statement
                    return;
                }

                let fn_name = format!("fsol_{}", target.to_lowercase());
                self.emit_instr(&format!("call {}", fn_name));
                self.emit("");
            }

            Statement::NestedFunction(f) => {
                // just emit the call here - the function body is already
                // emitted separately by the top-level block iterator
                let fn_label = format!("fsol_{}", f.name.to_lowercase());
                self.emit_comment(&format!("call nested: {}", f.name));
                self.emit_instr(&format!("call {}", fn_label));
                self.emit("");
            }

            Statement::Rei { signal, source, body } => {
                let skip = self.next_label();
                self.emit_comment(&format!(
                    "rei {} {}",
                    signal,
                    source.as_deref().map(|s| format!("from {}", s)).unwrap_or_default()
                ));
                self.emit_instr(&format!(
                    "cmp  byte [fsol_signal_{}], 1", signal
                ));
                self.emit_instr(&format!("jne NEAR {}", skip));
                for s in body { self.gen_statement(s); }
                self.emit_label(&skip);
                self.emit("");
            }

            Statement::Insp { kind, body } => {
                self.emit_comment(&format!("insp-{} check", kind));
                self.emit_instr(&format!("call fsol_insp_{}", kind));
                self.emit("");
                self.gen_insp_arms(body);
            }

            Statement::Broadcast { signal, target } => {
                self.emit_comment(&format!("broadcast {} -> {}", signal, target));
                if !self.signals.contains(signal) {
                    self.signals.push(signal.clone());
                }
                self.emit_instr(&format!(
                    "mov  byte [fsol_signal_{}], 1", signal
                ));
                self.emit_instr(&format!("call fsol_{}", target.to_lowercase()));
                self.emit("");
            }

            Statement::Dis { target, address } => {
                self.emit_comment(&format!("dis {} 0x{:X}", target, address));
                // VGA text buffer base is 0xB8000
                self.emit_instr("mov  rdi, 0xB8000");
                self.emit_instr(&format!("add  rdi, 0x{:X}", address * 2));
                self.emit_instr("mov  ax,  0x0741   ; grey 'A' as placeholder");
                self.emit_instr("mov  [rdi], ax");
                self.emit("");
            }

            Statement::Export { name, target } => {
                self.emit_comment(&format!("export {} -> {}", name, target));
                // define a local label for the exported name
                self.emit_label(&format!("fsol_{}", name.to_lowercase()));
                self.emit_instr(&format!("call fsol_{}", target.to_lowercase()));
                self.emit("");
            }

            Statement::Take { source, target } => {
                self.emit_comment(&format!("take {} -> {}", source, target));
                self.emit_instr(&format!("call fsol_{}", target.to_lowercase()));
                self.emit("");
            }

            Statement::Print { message } => {
                let lbl = format!("str_{}", self.label);
                self.label += 1;
                self.emit_comment(&format!("print \"{}\"", message));
                self.data(&format!("{}: db `{}`, 0", lbl, message));
                self.emit_instr(&format!("lea  rdi, [{}]", lbl));
                self.emit_instr("call fsol_print_str");
                self.emit("");
            }

            Statement::ListBlock { commands } => {
                self.emit_comment("command registry (descriptions)");
                for cmd in commands {
                    self.emit_comment(&format!("  {} - {}", cmd.name, cmd.description));
                }
                self.emit("");
            }

            Statement::CommandFunction { mappings } => {
                self.gen_command_function(mappings);
            }

            Statement::FuncMapping(fm) => {
                if let FuncAction::Assign { name, .. } = &fm.action {
                    if name == "_skip" { return; }
                }
                // standalone func mappings handled inside Call
            }
        }
    }

    // ---- insp conditional arms ----
    // FSOL insp structure:
    //   if: condition is failure  → try: run panic body
    //   else if: condition is success → run success body

    fn gen_insp_arms(&mut self, arms: &[InspArm]) {
        // collect arms by type
        let if_arm    = arms.iter().find(|a| matches!(a, InspArm::If { .. }));
        let try_arm   = arms.iter().find(|a| matches!(a, InspArm::Try { .. }));
        let elif_arm  = arms.iter().find(|a| matches!(a, InspArm::ElseIf { .. }));

        let success_label = self.next_label();
        let done_label    = self.next_label();

        // insp returns 0 in al = all loaded ok, nonzero = failure
        if let Some(InspArm::If { .. }) = if_arm {
            self.emit_comment("if load failed (al != 0) → panic");
            self.emit_instr("test al, al");
            self.emit_instr(&format!("jz   NEAR {}", success_label)); // jump to success if ok
        }

        // try block = panic path (runs when load failed)
        if let Some(InspArm::Try { body }) = try_arm {
            self.emit_comment("try: panic path");
            for s in body { self.gen_statement(s); }
            self.emit_instr(&format!("jmp NEAR {}", done_label));
            self.emit("");
        }

        // else if = success path
        self.emit_label(&success_label);
        if let Some(InspArm::ElseIf { body, .. }) = elif_arm {
            self.emit_comment("else if: success path");
            for s in body { self.gen_statement(s); }
        }

        self.emit_label(&done_label);
        self.emit("");
    }

    fn gen_insp_arm(&mut self, _arm: &InspArm) {
        // individual arms handled by gen_insp_arms above
    }

    // ---- command dispatcher ----

    fn gen_command_function(&mut self, mappings: &[CommandMapping]) {
        // filter out _skip placeholders first so label numbers are contiguous
        let real: Vec<&CommandMapping> = mappings.iter()
            .filter(|m| m.name != "_skip" && !m.name.is_empty() && !m.executor.is_empty())
            .collect();

        // always emit the label so the extern reference resolves
        self.emit_comment("command dispatcher");
        self.emit_label("fsol_commandfunction");
        self.emit_instr("push rbp");
        self.emit_instr("mov  rbp, rsp");
        self.emit("");

        if real.is_empty() {
            self.emit_comment("stub - no commands parsed yet");
            self.emit_instr("call fsol_unknown_cmd");
            self.emit_label("fsol_commandfunction.done");
            self.emit_instr("pop  rbp");
            self.emit_instr("ret");
            self.emit("");
            return;
        }

        for (i, m) in real.iter().enumerate() {
            let lbl  = format!("fsol_commandfunction.cmd_{}", i);
            let next = format!("fsol_commandfunction.cmd_{}", i + 1);
            let skey = format!("cmd_str_{}", i);
            self.data(&format!("{}: db `{}`, 0", skey, m.name));
            self.emit_label(&lbl);
            self.emit_comment(&format!("check '{}'", m.name));
            self.emit_instr(&format!("lea  rsi, [{}]", skey));
            self.emit_instr("call fsol_strcmp");
            self.emit_instr(&format!("jnz NEAR {}", next));
            self.emit_instr(&format!("call fsol_{}", m.executor.to_lowercase()));
            self.emit_instr("jmp NEAR fsol_commandfunction.done");
            self.emit("");
        }

        // final fallthrough label - unknown command
        self.emit_label(&format!("fsol_commandfunction.cmd_{}", real.len()));
        self.emit_comment("unknown command");
        self.emit_instr("call fsol_unknown_cmd");

        self.emit_label("fsol_commandfunction.done");
        self.emit_instr("pop  rbp");
        self.emit_instr("ret");
        self.emit("");
    }

    // ---- built-in runtime ----

    fn emit_runtime(&mut self) {
        self.emit("; ================================================================");
        self.emit("; FSOL Runtime - built-in kernel primitives");
        self.emit("; ================================================================");
        self.emit("");

        // fsol_panic
        self.emit_label("fsol_panic");
        self.emit_instr("mov  rsi, 0xB8000");
        self.emit_instr("mov  ah,  0x4F          ; white on red");
        for (i, ch) in "PANIC".chars().enumerate() {
            self.emit_instr(&format!("mov  al,  '{}'", ch));
            self.emit_instr(&format!("mov  [rsi+{}], ax", i * 2));
        }
        self.emit_label("fsol_panic.halt");
        self.emit_instr("cli");
        self.emit_instr("hlt");
        self.emit_instr("jmp NEAR fsol_panic.halt");
        self.emit("");

        // fsol_dis
        self.emit_label("fsol_dis");
        self.emit_instr("; rdi = VGA offset, sil = byte");
        self.emit_instr("mov  rax, 0xB8000");
        self.emit_instr("add  rax, rdi");
        self.emit_instr("mov  [rax], sil");
        self.emit_instr("ret");
        self.emit("");

        // fsol_print_str
        self.emit_label("fsol_print_str");
        self.emit_instr("; rdi = null-terminated string");
        self.emit_instr("push rbx");
        self.emit_instr("mov  rbx, 0xB8000");
        self.emit_instr("mov  ah,  0x07");
        self.emit_label("fsol_print_str.loop");
        self.emit_instr("mov  al, [rdi]");
        self.emit_instr("test al, al");
        self.emit_instr("jz  NEAR fsol_print_str.done");
        self.emit_instr("mov  [rbx], ax");
        self.emit_instr("add  rbx, 2");
        self.emit_instr("inc  rdi");
        self.emit_instr("jmp NEAR fsol_print_str.loop");
        self.emit_label("fsol_print_str.done");
        self.emit_instr("pop  rbx");
        self.emit_instr("ret");
        self.emit("");

        // fsol_strcmp
        self.emit_label("fsol_strcmp");
        self.emit_instr("; rdi=s1, rsi=s2 → ZF set if equal");
        self.emit_instr("push rbx");
        self.emit_label("fsol_strcmp.loop");
        self.emit_instr("mov  al, [rdi]");
        self.emit_instr("mov  bl, [rsi]");
        self.emit_instr("cmp  al, bl");
        self.emit_instr("jne NEAR fsol_strcmp.done");
        self.emit_instr("test al, al");
        self.emit_instr("jz  NEAR fsol_strcmp.done");
        self.emit_instr("inc  rdi");
        self.emit_instr("inc  rsi");
        self.emit_instr("jmp NEAR fsol_strcmp.loop");
        self.emit_label("fsol_strcmp.done");
        self.emit_instr("pop  rbx");
        self.emit_instr("ret");
        self.emit("");

        // fsol_unknown_cmd
        self.emit_label("fsol_unknown_cmd");
        self.emit_instr("mov  rdi, 0xB8000");
        self.emit_instr("mov  ax,  0x073F        ; '?' grey on black");
        self.emit_instr("mov  [rdi], ax");
        self.emit_instr("ret");
        self.emit("");
    }
}
